#
# linux/drivers/socle_nand/Makefile
#
# $Id: Makefile.common,v 1.15 2004/11/26 12:28:22 dedekind Exp $

obj-$(CONFIG_MTD_SOCLE_NAND)		+= socle_nand.o
obj-$(CONFIG_MTD_SOCLE_NAND_IDS)	+= socle_nand_ids.o
obj-$(CONFIG_MTD_SOCLE_NAND_GENERIC)   	+= socle_nand_generic.o

socle_nand-objs := socle_nand_base.o socle_nand_bbt.o

obj-y += rscode-1.0_socle/

